# Generated by Django 5.0.6 on 2024-05-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagmentSystemApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('user_type', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
