# Generated by Django 5.0.6 on 2024-05-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagmentSystemApp', '0003_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
