# Generated by Django 5.0.6 on 2024-05-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagmentSystemApp', '0004_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('cover_image', models.FileField(upload_to='cover/')),
                ('book_pdf', models.FileField(blank=True, upload_to='book/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
