# Generated by Django 5.0.6 on 2024-05-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagmentSystemApp', '0005_book_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='cover/'),
        ),
    ]
